import { sortTriageDashboardRows, type ClinicianTriageDashboardRow } from '@/lib/clinicians/clinician-triage-dashboard'

export type WearableSource = 'tiptraq' | 'oura' | 'whoop' | 'apple'

export type TriageMockPatient = ClinicianTriageDashboardRow & {
  wearable_source: WearableSource
  bti_delay_minutes: number | null
}

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 3_600_000).toISOString()

/** 10 TipTraQ premium + 4 standard wearable — local SPA mock (no Supabase). */
export const TRIAGE_MOCK_COHORT: TriageMockPatient[] = [
  {
    patient_id: 'elena-001',
    patient_name: 'Elena R.',
    patient_ref: 'RED-001',
    protocol: 'coimbra',
    is_premium_tier: true,
    device_alert_triggered: true,
    triage_status: 'URGENT',
    pth_pgml: 6,
    pth_trend: 'down',
    next_lab_due: '2026-05-28',
    last_telemetry_sync_at: hoursAgo(52),
    enrolled_at: '2025-08-14',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 112,
  },
  {
    patient_id: 'wb-apple-001',
    patient_name: 'Priya N.',
    patient_ref: 'WB-004',
    protocol: 'circadian',
    is_premium_tier: false,
    device_alert_triggered: true,
    triage_status: 'REVIEW',
    pth_pgml: 41,
    pth_trend: 'flat',
    next_lab_due: '2026-06-18',
    last_telemetry_sync_at: null,
    enrolled_at: '2026-01-20',
    primary_medication_id: 'metformin',
    clinician_id: null,
    wearable_source: 'apple',
    bti_delay_minutes: 68,
  },
  {
    patient_id: 'tq-007',
    patient_name: 'James Okonkwo',
    patient_ref: 'TQ-007',
    protocol: 'coimbra',
    is_premium_tier: true,
    device_alert_triggered: true,
    triage_status: 'URGENT',
    pth_pgml: 72,
    pth_trend: 'up',
    next_lab_due: '2026-06-02',
    last_telemetry_sync_at: hoursAgo(41),
    enrolled_at: '2025-10-03',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 98,
  },
  {
    patient_id: 'marcus-001',
    patient_name: 'Marcus H.',
    patient_ref: 'AMB-001',
    protocol: 'gominak',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'REVIEW',
    pth_pgml: 46,
    pth_trend: 'flat',
    next_lab_due: '2026-06-08',
    last_telemetry_sync_at: hoursAgo(8),
    enrolled_at: '2025-10-02',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 68,
  },
  {
    patient_id: 'wb-whoop-001',
    patient_name: 'Tomás V.',
    patient_ref: 'WB-002',
    protocol: 'circadian',
    is_premium_tier: false,
    device_alert_triggered: false,
    triage_status: 'REVIEW',
    pth_pgml: 48,
    pth_trend: 'up',
    next_lab_due: '2026-07-01',
    last_telemetry_sync_at: hoursAgo(6),
    enrolled_at: '2026-02-11',
    primary_medication_id: 'lisinopril',
    clinician_id: null,
    wearable_source: 'whoop',
    bti_delay_minutes: 54,
  },
  {
    patient_id: 'sean-001',
    patient_name: 'Sean James',
    patient_ref: 'SEAN-001',
    protocol: 'coimbra',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 38,
    pth_trend: 'down',
    next_lab_due: '2026-07-15',
    last_telemetry_sync_at: hoursAgo(4),
    enrolled_at: '2025-11-01',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 94,
  },
  {
    patient_id: 'tq-001',
    patient_name: 'Amara Singh',
    patient_ref: 'TQ-001',
    protocol: 'coimbra',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 28,
    pth_trend: 'down',
    next_lab_due: '2026-08-01',
    last_telemetry_sync_at: hoursAgo(3),
    enrolled_at: '2025-12-12',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 76,
  },
  {
    patient_id: 'tq-002',
    patient_name: 'Helena Costa',
    patient_ref: 'TQ-002',
    protocol: 'coimbra',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 24,
    pth_trend: 'down',
    next_lab_due: '2026-08-14',
    last_telemetry_sync_at: hoursAgo(5),
    enrolled_at: '2026-01-05',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 61,
  },
  {
    patient_id: 'tq-003',
    patient_name: 'David Kim',
    patient_ref: 'TQ-003',
    protocol: 'gominak',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'REVIEW',
    pth_pgml: 44,
    pth_trend: 'flat',
    next_lab_due: '2026-06-22',
    last_telemetry_sync_at: hoursAgo(7),
    enrolled_at: '2025-11-18',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 82,
  },
  {
    patient_id: 'wb-oura-001',
    patient_name: 'Claire M.',
    patient_ref: 'WB-001',
    protocol: 'circadian',
    is_premium_tier: false,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 32,
    pth_trend: 'down',
    next_lab_due: '2026-09-01',
    last_telemetry_sync_at: hoursAgo(9),
    enrolled_at: '2026-03-01',
    primary_medication_id: 'atorvastatin',
    clinician_id: null,
    wearable_source: 'oura',
    bti_delay_minutes: 45,
  },
  {
    patient_id: 'tq-004',
    patient_name: 'Fatima Al-Rashid',
    patient_ref: 'TQ-004',
    protocol: 'coimbra',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 31,
    pth_trend: 'down',
    next_lab_due: '2026-07-28',
    last_telemetry_sync_at: hoursAgo(2),
    enrolled_at: '2025-10-28',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 88,
  },
  {
    patient_id: 'tq-005',
    patient_name: 'Robert Ellis',
    patient_ref: 'TQ-005',
    protocol: 'coimbra',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 27,
    pth_trend: 'flat',
    next_lab_due: '2026-08-05',
    last_telemetry_sync_at: hoursAgo(11),
    enrolled_at: '2025-09-14',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 71,
  },
  {
    patient_id: 'tq-006',
    patient_name: 'Yuki Tanaka',
    patient_ref: 'TQ-006',
    protocol: 'gominak',
    is_premium_tier: true,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 29,
    pth_trend: 'down',
    next_lab_due: '2026-07-20',
    last_telemetry_sync_at: hoursAgo(6),
    enrolled_at: '2025-11-22',
    primary_medication_id: 'vitamin-d3',
    clinician_id: null,
    wearable_source: 'tiptraq',
    bti_delay_minutes: 59,
  },
  {
    patient_id: 'wb-oura-002',
    patient_name: 'Liam O.',
    patient_ref: 'WB-003',
    protocol: 'circadian',
    is_premium_tier: false,
    device_alert_triggered: false,
    triage_status: 'ON_TRACK',
    pth_pgml: 35,
    pth_trend: 'flat',
    next_lab_due: '2026-10-01',
    last_telemetry_sync_at: hoursAgo(12),
    enrolled_at: '2026-04-02',
    primary_medication_id: 'sertraline',
    clinician_id: null,
    wearable_source: 'oura',
    bti_delay_minutes: 39,
  },
]

export function getLocalTriageCohort(): TriageMockPatient[] {
  return sortTriageDashboardRows(TRIAGE_MOCK_COHORT) as TriageMockPatient[]
}

export function getTriageMockPatient(id: string): TriageMockPatient | undefined {
  return TRIAGE_MOCK_COHORT.find((patient) => patient.patient_id === id)
}
